// Original supplied GIF animation frames. Horizontal sheets; frame 0 is the ready pose.
export const characters = [
  {
    "id": "hataalii",
    "combatSheet": "/assets/characters/hataalii-combat.png",
    "combatFrameCount": 28,
    "name": "HATAALII",
    "title": "The Original",
    "color": "#ff6148",
    "description": "Red cap. Black suit. No hesitation.",
    "move": "Crown Breaker",
    "speed": 8,
    "power": 7,
    "reach": 6,
    "sheet": "/assets/characters/hataalii-sheet.png",
    "portrait": "/assets/characters/hataalii-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 150
  },
  {
    "id": "urban",
    "combatSheet": "/assets/characters/urban-combat.png",
    "combatFrameCount": 28,
    "name": "AFTER HOURS",
    "title": "The Architect",
    "color": "#a8bfcf",
    "description": "A flowing coat and a perfectly timed backfist.",
    "move": "Midnight Backfist",
    "speed": 7,
    "power": 8,
    "reach": 8,
    "sheet": "/assets/characters/urban-sheet.png",
    "portrait": "/assets/characters/urban-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
  {
    "id": "gauntlet",
    "combatSheet": "/assets/characters/gauntlet-combat.png",
    "combatFrameCount": 28,
    "name": "IRON WILL",
    "title": "The Augmented",
    "color": "#3de2ef",
    "description": "Armored resolve with a charged cyan gauntlet.",
    "move": "Ion Burst",
    "speed": 5,
    "power": 10,
    "reach": 10,
    "sheet": "/assets/characters/gauntlet-sheet.png",
    "portrait": "/assets/characters/gauntlet-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
  {
    "id": "tote",
    "combatSheet": "/assets/characters/tote-combat.png",
    "combatFrameCount": 28,
    "name": "QUIET LUXURY",
    "title": "The Counterpuncher",
    "color": "#ddc3a2",
    "description": "Composure, a black cap, and an unexpected counter.",
    "move": "Executive Counter",
    "speed": 8,
    "power": 7,
    "reach": 7,
    "sheet": "/assets/characters/tote-sheet.png",
    "portrait": "/assets/characters/tote-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
  {
    "id": "vector",
    "combatSheet": "/assets/characters/vector-combat.png",
    "combatFrameCount": 28,
    "name": "BLUEPRINT",
    "title": "The Technician",
    "color": "#729cff",
    "description": "Precision footwork in head-to-toe indigo.",
    "move": "Vector Sidekick",
    "speed": 9,
    "power": 6,
    "reach": 9,
    "sheet": "/assets/characters/vector-sheet.png",
    "portrait": "/assets/characters/vector-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
  {
    "id": "kinetic",
    "combatSheet": "/assets/characters/kinetic-combat.png",
    "combatFrameCount": 28,
    "name": "GREEN LIGHT",
    "title": "The Juggernaut",
    "color": "#57df8f",
    "description": "A green-lined jacket and unstoppable forward motion.",
    "move": "Kinetic Shoulder",
    "speed": 6,
    "power": 9,
    "reach": 6,
    "sheet": "/assets/characters/kinetic-sheet.png",
    "portrait": "/assets/characters/kinetic-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
  {
    "id": "corvette",
    "combatSheet": "/assets/characters/corvette-combat.png",
    "combatFrameCount": 28,
    "name": "FAST LANE",
    "title": "The Showstopper",
    "color": "#ffcc55",
    "description": "Vintage Corvette tee. A kick with serious mileage.",
    "move": "Redline Kick",
    "speed": 9,
    "power": 7,
    "reach": 8,
    "sheet": "/assets/characters/corvette-sheet.png",
    "portrait": "/assets/characters/corvette-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
  {
    "id": "curly",
    "combatSheet": "/assets/characters/curly-combat.png",
    "combatFrameCount": 28,
    "name": "WILD CARD",
    "title": "The Freestyler",
    "color": "#d5d5e3",
    "description": "Loose curls, a black tee, and a sweep from nowhere.",
    "move": "Ground Zero Sweep",
    "speed": 10,
    "power": 6,
    "reach": 7,
    "sheet": "/assets/characters/curly-sheet.png",
    "portrait": "/assets/characters/curly-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
  {
    "id": "pixel",
    "combatSheet": "/assets/characters/pixel-combat.png",
    "combatFrameCount": 28,
    "name": "SHADOW SELF",
    "title": "The Instinct",
    "color": "#b093fc",
    "description": "The raw pixel original, fighting on pure instinct.",
    "move": "Mirror Shatter",
    "speed": 8,
    "power": 8,
    "reach": 8,
    "sheet": "/assets/characters/pixel-sheet.png",
    "portrait": "/assets/characters/pixel-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 180
  },
  {
    "id": "tweed",
    "combatSheet": "/assets/characters/tweed-combat.png",
    "combatFrameCount": 28,
    "name": "OLD SOUL",
    "title": "The Gentleman",
    "color": "#cfa075",
    "description": "Tweed, a flat cap, and an ungentlemanly uppercut.",
    "move": "Heritage Uppercut",
    "speed": 6,
    "power": 9,
    "reach": 6,
    "sheet": "/assets/characters/tweed-sheet.png",
    "portrait": "/assets/characters/tweed-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
  {
    "id": "varsity",
    "combatSheet": "/assets/characters/varsity-combat.png",
    "combatFrameCount": 28,
    "name": "VARSITY",
    "title": "The All-Star",
    "color": "#f48aab",
    "description": "Burgundy varsity jacket. Championship intensity.",
    "move": "Overtime Elbow",
    "speed": 8,
    "power": 8,
    "reach": 6,
    "sheet": "/assets/characters/varsity-sheet.png",
    "portrait": "/assets/characters/varsity-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 170
  }
];
export default characters;
