// Every fighter shares one atlas layout: a 16-frame ready sheet (frame 0 is the idle pose),
// a 4×7 combat atlas, a 4×6 motion atlas and a portrait, all on 320×320 cells grounded at y=296.
// bodyHeight is the visible ready-pose height; combat scales every fighter to the same on-screen size.
// motionBodyHeight is the height the motion atlas was packed at, when that differs from the combat atlas.
export const REFERENCE_BODY = 176;
// Menu art draws the raw 320px cells; this factor brings a shorter-drawn body up to the shared height.
export const bodyScale = (c) => Math.round((REFERENCE_BODY / (c?.bodyHeight || REFERENCE_BODY)) * 1000) / 1000;
const fighter = ({ id, bodyHeight = REFERENCE_BODY, motionBodyHeight = bodyHeight, ...identity }) => ({
  id,
  ...identity,
  sheet: `/assets/characters/${id}-sheet.png`,
  combatSheet: `/assets/characters/${id}-combat.png`,
  motionSheet: `/assets/characters/${id}-motion.png`,
  portrait: `/assets/characters/${id}-portrait.png`,
  frameWidth: 320,
  frameHeight: 320,
  frameCount: 16,
  frameDuration: 65,
  combatFrameCount: 28,
  motionFrameCount: 24,
  bodyHeight,
  motionBodyHeight,
  anchorX: 160,
  anchorY: 296,
});

export const characters = [
  // The original eleven, from the supplied battle-animation GIFs.
  fighter({
    id: "hataalii",
    name: "HATAALII",
    title: "The Original",
    color: "#ff6148",
    description: "Red cap. Black suit. No hesitation.",
    move: "Crown Breaker",
    quote: "Every version of me started as this one.",
    speed: 8,
    power: 7,
    reach: 6,
  }),
  fighter({
    id: "urban",
    name: "AFTER HOURS",
    title: "The Architect",
    color: "#a8bfcf",
    description: "A flowing coat and a perfectly timed backfist.",
    move: "Midnight Backfist",
    quote: "The night was quiet until you made a sound.",
    speed: 7,
    power: 8,
    reach: 8,
  }),
  fighter({
    id: "gauntlet",
    name: "IRON WILL",
    title: "The Augmented",
    color: "#3de2ef",
    description: "Armored resolve with a charged cyan gauntlet.",
    move: "Ion Burst",
    quote: "Charged, aimed and finished before you moved.",
    speed: 5,
    power: 10,
    reach: 10,
  }),
  fighter({
    id: "tote",
    name: "QUIET LUXURY",
    title: "The Counterpuncher",
    color: "#ddc3a2",
    description: "Composure, a black cap, and an unexpected counter.",
    move: "Executive Counter",
    quote: "I let you speak first; that was the mistake.",
    speed: 8,
    power: 7,
    reach: 7,
  }),
  fighter({
    id: "vector",
    name: "BLUEPRINT",
    title: "The Technician",
    color: "#729cff",
    description: "Precision footwork in head-to-toe indigo.",
    move: "Vector Sidekick",
    quote: "Angles do not lie, and your footwork did.",
    speed: 9,
    power: 6,
    reach: 9,
  }),
  fighter({
    id: "kinetic",
    name: "GREEN LIGHT",
    title: "The Juggernaut",
    color: "#57df8f",
    description: "A green-lined jacket and unstoppable forward motion.",
    move: "Kinetic Shoulder",
    quote: "A green light means I never stop.",
    speed: 6,
    power: 9,
    reach: 6,
  }),
  fighter({
    id: "corvette",
    name: "FAST LANE",
    title: "The Showstopper",
    color: "#ffcc55",
    description: "Vintage Corvette tee. A kick with serious mileage.",
    move: "Redline Kick",
    quote: "Plenty of miles left on this kick.",
    speed: 9,
    power: 7,
    reach: 8,
  }),
  fighter({
    id: "curly",
    name: "WILD CARD",
    title: "The Freestyler",
    color: "#d5d5e3",
    description: "Loose curls, a black tee, and a sweep from nowhere.",
    move: "Ground Zero Sweep",
    quote: "You never saw the sweep because I never planned it.",
    speed: 10,
    power: 6,
    reach: 7,
  }),
  fighter({
    id: "pixel",
    name: "SHADOW SELF",
    title: "The Instinct",
    color: "#b093fc",
    description: "The raw pixel original, fighting on pure instinct.",
    move: "Mirror Shatter",
    quote: "Instinct is just a memory you forgot you had.",
    speed: 8,
    power: 8,
    reach: 8,
  }),
  fighter({
    id: "tweed",
    name: "OLD SOUL",
    title: "The Gentleman",
    color: "#cfa075",
    description: "Tweed, a flat cap, and an ungentlemanly uppercut.",
    move: "Heritage Uppercut",
    quote: "Manners are for after the fight.",
    speed: 6,
    power: 9,
    reach: 6,
  }),
  fighter({
    id: "varsity",
    name: "VARSITY",
    title: "The All-Star",
    color: "#f48aab",
    description: "Burgundy varsity jacket. Championship intensity.",
    move: "Overtime Elbow",
    quote: "Championship habits: grab, drop, repeat.",
    speed: 8,
    power: 8,
    reach: 6,
  }),
  // Nine-fighter expansion, interpreted from supplied photographic references.
  fighter({
    id: "hybrid",
    name: "HYBRID",
    title: "The Dualist",
    color: "#e5a949",
    description: "Two disciplines. An amber orbit held in one palm.",
    move: "Fusion Orbit",
    quote: "Two disciplines, one outcome.",
    speed: 8,
    power: 8,
    reach: 7,
  }),
  fighter({
    id: "civic",
    name: "CIVIC SAGE",
    title: "The Peacemaker",
    color: "#a5ce9f",
    description: "Pale green composure. A jade ward behind every shoulder strike.",
    move: "Accord Ward",
    quote: "Peace comes easier once you stop swinging.",
    speed: 6,
    power: 9,
    reach: 7,
  }),
  fighter({
    id: "nexus",
    name: "NEXUS",
    title: "The Connector",
    color: "#c6e2ef",
    description: "Black and white tracksuit. A sonic pulse from an open palm.",
    move: "Pulse Relay",
    quote: "Signal received; connection terminated.",
    speed: 10,
    power: 6,
    reach: 8,
  }),
  fighter({
    id: "glyph",
    name: "GLYPH",
    title: "The Inscriber",
    color: "#cb728c",
    description: "Burgundy beanie. Dark hoodie. A signature written in force.",
    move: "Crimson Forge",
    quote: "That was my signature, so keep it.",
    speed: 7,
    power: 8,
    reach: 9,
  }),
  fighter({
    id: "quilt",
    name: "QUILT",
    title: "The Unruffled",
    color: "#ed9dc7",
    description: "White puffer, navy accents, and a perfectly timed tote counter.",
    move: "Cloudburst Counter",
    quote: "Unruffled, and now you know why.",
    speed: 8,
    power: 7,
    reach: 9,
  }),
  fighter({
    id: "binary",
    name: "BINARY",
    title: "The Disruptor",
    color: "#99b8bd",
    description: "Black scarf. Cargo pockets. Break the pattern.",
    move: "Null Sweep",
    quote: "Your pattern broke on the first input.",
    speed: 9,
    power: 7,
    reach: 7,
  }),
  fighter({
    id: "aether",
    name: "AETHER",
    title: "The Sunrunner",
    color: "#ffa355",
    description: "Cream and orange. A bright streak across the arena.",
    move: "Solar Cyclone",
    quote: "I was already at the finish line.",
    speed: 9,
    power: 7,
    reach: 8,
  }),
  fighter({
    id: "gaia",
    name: "GAIA",
    title: "The Alchemist",
    color: "#72d6a8",
    description: "A scientist in a lab coat with an unstable new formula.",
    move: "Root Uprising",
    quote: "The formula was stable; you were not.",
    speed: 5,
    power: 9,
    reach: 10,
  }),
  fighter({
    id: "zenith",
    name: "ZENITH",
    title: "The Strategist",
    color: "#b5a5ee",
    description: "Braids, glasses, and a gray turtleneck. Always one step ahead.",
    move: "Apex Pulse",
    quote: "I planned this three rounds ago.",
    speed: 7,
    power: 9,
    reach: 6,
  }),
  // Seven-fighter expansion. bodyHeight comes from each export manifest.
  fighter({
    id: "archer",
    name: "EVERGREEN",
    title: "The Marksman",
    color: "#8fd44a",
    description: "A leaf cloak, a longbow, and a volley that never misses twice.",
    move: "Verdant Volley",
    quote: "I only needed one clear line.",
    speed: 7,
    power: 6,
    reach: 10,
  }),
  fighter({
    id: "cyborg",
    name: "OVERCLOCK",
    title: "The Upgrade",
    color: "#4fd6ff",
    description: "Black trench coat, gold circuitry, and a fist running hot.",
    move: "Plasma Rush",
    quote: "Patched, upgraded and still running hot.",
    speed: 8,
    power: 9,
    reach: 6,
    bodyHeight: 169,
  }),
  fighter({
    id: "eon",
    name: "EON",
    title: "The Timeless",
    color: "#a77dff",
    description: "Cream sweats, gray beanie, and all the time in the world.",
    move: "Hourglass Rift",
    quote: "I have seen this ending a thousand times.",
    speed: 6,
    power: 8,
    reach: 9,
    bodyHeight: 156,
    motionBodyHeight: 176, // motion atlas was packed under juris in the supplied export
  }),
  fighter({
    id: "juris",
    name: "JURIS",
    title: "The Arbiter",
    color: "#e2bd5c",
    description: "Navy beret, gold crest. Every grab is a binding verdict.",
    move: "Verdict Shield",
    quote: "The verdict is final; no appeals.",
    speed: 6,
    power: 10,
    reach: 6,
    motionBodyHeight: 143, // motion atlas was packed under student in the supplied export
  }),
  fighter({
    id: "nomad",
    name: "NOMAD",
    title: "The Wanderer",
    color: "#ffb02e",
    description: "Gold-striped tracksuit. Carries a campfire in one fist.",
    move: "Caravan Flare",
    quote: "Every road ends somewhere; yours ended here.",
    speed: 8,
    power: 7,
    reach: 9,
  }),
  fighter({
    id: "sketch",
    name: "SKETCH",
    title: "The Draft",
    color: "#e6e6e6",
    description: "Drawn in graphite. One clean stroke erases the rest.",
    move: "Graphite Stroke",
    quote: "A rough draft, and you still could not read it.",
    speed: 9,
    power: 7,
    reach: 8,
    bodyHeight: 168,
  }),
  fighter({
    id: "student",
    name: "STUDENT",
    title: "The Prodigy",
    color: "#ffe29a",
    description: "Backpack on, book open. Class is in session.",
    move: "Page Storm",
    quote: "Study hard, hit harder.",
    speed: 10,
    power: 6,
    reach: 8,
    bodyHeight: 143,
    motionBodyHeight: 156, // motion atlas was packed under eon in the supplied export
  }),
  // Eight-fighter photo-reference pack.
  fighter({ id: "patchrunner", name: "PATCHRUNNER", title: "The Fixer", color: "#ffa933", description: "Black vest, amber circuits, and a charge that jumps the gap.", move: "Circuit Cascade", quote: "Every system has an opening.", speed: 9, power: 7, reach: 8, bodyHeight: 176 }),
  fighter({ id: "starscribe", name: "STAR SCRIBE", title: "The Astral", color: "#9ba8ff", description: "Star-draped robe and orbiting staff.", move: "Orbit Collapse", quote: "I wrote this outcome in the stars.", speed: 6, power: 8, reach: 10, bodyHeight: 148 }),
  fighter({ id: "sovereign", name: "SOVEREIGN", title: "The Crown", color: "#eac35e", description: "Fur-trimmed mantle and a royal gambit.", move: "Royal Gambit", quote: "Your next move is already mine.", speed: 6, power: 10, reach: 7, bodyHeight: 136 }),
  fighter({ id: "circuitbreaker", name: "CIRCUIT BREAKER", title: "The Hacker", color: "#58ea88", description: "Circuit boards and a green systems breach.", move: "System Override", quote: "Access granted. Control revoked.", speed: 8, power: 7, reach: 9, bodyHeight: 176 }),
  fighter({ id: "ironchef", name: "IRON CHEF", title: "The Flame", color: "#f6a347", description: "Navy chef coat and a searing signature dish.", move: "Inferno Platter", quote: "The heat was always intentional.", speed: 7, power: 8, reach: 8, bodyHeight: 172 }),
  fighter({ id: "eventhorizon", name: "EVENT HORIZON", title: "The Explorer", color: "#b792ff", description: "Violet spacesuit and a pocket gravity well.", move: "Singularity Drive", quote: "You crossed the point of no return.", speed: 5, power: 9, reach: 10, bodyHeight: 172 }),
  fighter({ id: "crimsonoracle", name: "CRIMSON ORACLE", title: "The Seer", color: "#f34d65", description: "Red runes and a sealed fate.", move: "Blood Moon Seal", quote: "I saw you coming.", speed: 7, power: 9, reach: 8, bodyHeight: 157 }),
  fighter({ id: "dunevoyager", name: "DUNE VOYAGER", title: "The Pathfinder", color: "#dca35f", description: "Expedition gear and a spiral of desert sand.", move: "Sandstorm Break", quote: "The desert keeps its own score.", speed: 8, power: 7, reach: 9, bodyHeight: 176 }),
];
export default characters;
