// Original supplied GIF animation frames. Horizontal sheets; frame 0 is the ready pose.
export const characters = [
  {
    id: "hataalii",
    combatSheet: "/assets/characters/hataalii-combat.png",
    motionSheet: "/assets/characters/hataalii-motion.png",
    motionFrameCount: 24,
    combatFrameCount: 28,
    name: "HATAALII",
    title: "The Original",
    color: "#ff6148",
    description: "Red cap. Black suit. No hesitation.",
    move: "Crown Breaker",
    speed: 8,
    power: 7,
    reach: 6,
    sheet: "/assets/characters/hataalii-sheet.png",
    portrait: "/assets/characters/hataalii-portrait.png",
    frameWidth: 320,
    frameHeight: 320,
    frameCount: 16,
    frameDuration: 65,
    bodyHeight: 176,
    anchorX: 160,
    anchorY: 296,
    originalDuration: 150,
  },
  {
    id: "urban",
    combatSheet: "/assets/characters/urban-combat.png",
    motionSheet: "/assets/characters/urban-motion.png",
    motionFrameCount: 24,
    combatFrameCount: 28,
    name: "AFTER HOURS",
    title: "The Architect",
    color: "#a8bfcf",
    description: "A flowing coat and a perfectly timed backfist.",
    move: "Midnight Backfist",
    speed: 7,
    power: 8,
    reach: 8,
    sheet: "/assets/characters/urban-sheet.png",
    portrait: "/assets/characters/urban-portrait.png",
    frameWidth: 320,
    frameHeight: 320,
    frameCount: 16,
    frameDuration: 65,
    bodyHeight: 176,
    anchorX: 160,
    anchorY: 296,
    originalDuration: 160,
  },
  {
    id: "gauntlet",
    combatSheet: "/assets/characters/gauntlet-combat.png",
    motionSheet: "/assets/characters/gauntlet-motion.png",
    motionFrameCount: 24,
    combatFrameCount: 28,
    name: "IRON WILL",
    title: "The Augmented",
    color: "#3de2ef",
    description: "Armored resolve with a charged cyan gauntlet.",
    move: "Ion Burst",
    speed: 5,
    power: 10,
    reach: 10,
    sheet: "/assets/characters/gauntlet-sheet.png",
    portrait: "/assets/characters/gauntlet-portrait.png",
    frameWidth: 320,
    frameHeight: 320,
    frameCount: 16,
    frameDuration: 65,
    bodyHeight: 176,
    anchorX: 160,
    anchorY: 296,
    originalDuration: 160,
  },
  {
    id: "tote",
    combatSheet: "/assets/characters/tote-combat.png",
    motionSheet: "/assets/characters/tote-motion.png",
    motionFrameCount: 24,
    combatFrameCount: 28,
    name: "QUIET LUXURY",
    title: "The Counterpuncher",
    color: "#ddc3a2",
    description: "Composure, a black cap, and an unexpected counter.",
    move: "Executive Counter",
    speed: 8,
    power: 7,
    reach: 7,
    sheet: "/assets/characters/tote-sheet.png",
    portrait: "/assets/characters/tote-portrait.png",
    frameWidth: 320,
    frameHeight: 320,
    frameCount: 16,
    frameDuration: 65,
    bodyHeight: 176,
    anchorX: 160,
    anchorY: 296,
    originalDuration: 160,
  },
  {
    id: "vector",
    combatSheet: "/assets/characters/vector-combat.png",
    motionSheet: "/assets/characters/vector-motion.png",
    motionFrameCount: 24,
    combatFrameCount: 28,
    name: "BLUEPRINT",
    title: "The Technician",
    color: "#729cff",
    description: "Precision footwork in head-to-toe indigo.",
    move: "Vector Sidekick",
    speed: 9,
    power: 6,
    reach: 9,
    sheet: "/assets/characters/vector-sheet.png",
    portrait: "/assets/characters/vector-portrait.png",
    frameWidth: 320,
    frameHeight: 320,
    frameCount: 16,
    frameDuration: 65,
    bodyHeight: 176,
    anchorX: 160,
    anchorY: 296,
    originalDuration: 160,
  },
  {
    id: "kinetic",
    combatSheet: "/assets/characters/kinetic-combat.png",
    motionSheet: "/assets/characters/kinetic-motion.png",
    motionFrameCount: 24,
    combatFrameCount: 28,
    name: "GREEN LIGHT",
    title: "The Juggernaut",
    color: "#57df8f",
    description: "A green-lined jacket and unstoppable forward motion.",
    move: "Kinetic Shoulder",
    speed: 6,
    power: 9,
    reach: 6,
    sheet: "/assets/characters/kinetic-sheet.png",
    portrait: "/assets/characters/kinetic-portrait.png",
    frameWidth: 320,
    frameHeight: 320,
    frameCount: 16,
    frameDuration: 65,
    bodyHeight: 176,
    anchorX: 160,
    anchorY: 296,
    originalDuration: 160,
  },
  {
    id: "corvette",
    combatSheet: "/assets/characters/corvette-combat.png",
    motionSheet: "/assets/characters/corvette-motion.png",
    motionFrameCount: 24,
    combatFrameCount: 28,
    name: "FAST LANE",
    title: "The Showstopper",
    color: "#ffcc55",
    description: "Vintage Corvette tee. A kick with serious mileage.",
    move: "Redline Kick",
    speed: 9,
    power: 7,
    reach: 8,
    sheet: "/assets/characters/corvette-sheet.png",
    portrait: "/assets/characters/corvette-portrait.png",
    frameWidth: 320,
    frameHeight: 320,
    frameCount: 16,
    frameDuration: 65,
    bodyHeight: 176,
    anchorX: 160,
    anchorY: 296,
    originalDuration: 160,
  },
  {
    id: "curly",
    combatSheet: "/assets/characters/curly-combat.png",
    motionSheet: "/assets/characters/curly-motion.png",
    motionFrameCount: 24,
    combatFrameCount: 28,
    name: "WILD CARD",
    title: "The Freestyler",
    color: "#d5d5e3",
    description: "Loose curls, a black tee, and a sweep from nowhere.",
    move: "Ground Zero Sweep",
    speed: 10,
    power: 6,
    reach: 7,
    sheet: "/assets/characters/curly-sheet.png",
    portrait: "/assets/characters/curly-portrait.png",
    frameWidth: 320,
    frameHeight: 320,
    frameCount: 16,
    frameDuration: 65,
    bodyHeight: 176,
    anchorX: 160,
    anchorY: 296,
    originalDuration: 160,
  },
  {
    id: "pixel",
    combatSheet: "/assets/characters/pixel-combat.png",
    motionSheet: "/assets/characters/pixel-motion.png",
    motionFrameCount: 24,
    combatFrameCount: 28,
    name: "SHADOW SELF",
    title: "The Instinct",
    color: "#b093fc",
    description: "The raw pixel original, fighting on pure instinct.",
    move: "Mirror Shatter",
    speed: 8,
    power: 8,
    reach: 8,
    sheet: "/assets/characters/pixel-sheet.png",
    portrait: "/assets/characters/pixel-portrait.png",
    frameWidth: 320,
    frameHeight: 320,
    frameCount: 16,
    frameDuration: 65,
    bodyHeight: 176,
    anchorX: 160,
    anchorY: 296,
    originalDuration: 180,
  },
  {
    id: "tweed",
    combatSheet: "/assets/characters/tweed-combat.png",
    motionSheet: "/assets/characters/tweed-motion.png",
    motionFrameCount: 24,
    combatFrameCount: 28,
    name: "OLD SOUL",
    title: "The Gentleman",
    color: "#cfa075",
    description: "Tweed, a flat cap, and an ungentlemanly uppercut.",
    move: "Heritage Uppercut",
    speed: 6,
    power: 9,
    reach: 6,
    sheet: "/assets/characters/tweed-sheet.png",
    portrait: "/assets/characters/tweed-portrait.png",
    frameWidth: 320,
    frameHeight: 320,
    frameCount: 16,
    frameDuration: 65,
    bodyHeight: 176,
    anchorX: 160,
    anchorY: 296,
    originalDuration: 160,
  },
  {
    id: "varsity",
    combatSheet: "/assets/characters/varsity-combat.png",
    motionSheet: "/assets/characters/varsity-motion.png",
    motionFrameCount: 24,
    combatFrameCount: 28,
    name: "VARSITY",
    title: "The All-Star",
    color: "#f48aab",
    description: "Burgundy varsity jacket. Championship intensity.",
    move: "Overtime Elbow",
    speed: 8,
    power: 8,
    reach: 6,
    sheet: "/assets/characters/varsity-sheet.png",
    portrait: "/assets/characters/varsity-portrait.png",
    frameWidth: 320,
    frameHeight: 320,
    frameCount: 16,
    frameDuration: 65,
    bodyHeight: 176,
    anchorX: 160,
    anchorY: 296,
    originalDuration: 170,
  },
  {
    "id": "hybrid",
    "combatSheet": "/assets/characters/hybrid-combat.png",
    "motionSheet": "/assets/characters/hybrid-motion.png",
    "motionFrameCount": 24,
    "combatFrameCount": 28,
    "name": "HYBRID",
    "title": "The Dualist",
    "color": "#e5a949",
    "description": "Two disciplines. An amber orbit held in one palm.",
    "move": "Fusion Orbit",
    "speed": 8,
    "power": 8,
    "reach": 7,
    "sheet": "/assets/characters/hybrid-sheet.png",
    "portrait": "/assets/characters/hybrid-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
  {
    "id": "civic",
    "combatSheet": "/assets/characters/civic-combat.png",
    "motionSheet": "/assets/characters/civic-motion.png",
    "motionFrameCount": 24,
    "combatFrameCount": 28,
    "name": "CIVIC SAGE",
    "title": "The Peacemaker",
    "color": "#a5ce9f",
    "description": "Pale green composure. A jade ward behind every shoulder strike.",
    "move": "Accord Ward",
    "speed": 6,
    "power": 9,
    "reach": 7,
    "sheet": "/assets/characters/civic-sheet.png",
    "portrait": "/assets/characters/civic-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
  {
    "id": "nexus",
    "combatSheet": "/assets/characters/nexus-combat.png",
    "motionSheet": "/assets/characters/nexus-motion.png",
    "motionFrameCount": 24,
    "combatFrameCount": 28,
    "name": "NEXUS",
    "title": "The Connector",
    "color": "#c6e2ef",
    "description": "Black and white tracksuit. A sonic pulse from an open palm.",
    "move": "Pulse Relay",
    "speed": 10,
    "power": 6,
    "reach": 8,
    "sheet": "/assets/characters/nexus-sheet.png",
    "portrait": "/assets/characters/nexus-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
  {
    "id": "glyph",
    "combatSheet": "/assets/characters/glyph-combat.png",
    "motionSheet": "/assets/characters/glyph-motion.png",
    "motionFrameCount": 24,
    "combatFrameCount": 28,
    "name": "GLYPH",
    "title": "The Inscriber",
    "color": "#cb728c",
    "description": "Burgundy beanie. Dark hoodie. A signature written in force.",
    "move": "Crimson Forge",
    "speed": 7,
    "power": 8,
    "reach": 9,
    "sheet": "/assets/characters/glyph-sheet.png",
    "portrait": "/assets/characters/glyph-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
  {
    "id": "quilt",
    "combatSheet": "/assets/characters/quilt-combat.png",
    "motionSheet": "/assets/characters/quilt-motion.png",
    "motionFrameCount": 24,
    "combatFrameCount": 28,
    "name": "QUILT",
    "title": "The Unruffled",
    "color": "#ed9dc7",
    "description": "White puffer, navy accents, and a perfectly timed tote counter.",
    "move": "Cloudburst Counter",
    "speed": 8,
    "power": 7,
    "reach": 9,
    "sheet": "/assets/characters/quilt-sheet.png",
    "portrait": "/assets/characters/quilt-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
  {
    "id": "binary",
    "combatSheet": "/assets/characters/binary-combat.png",
    "motionSheet": "/assets/characters/binary-motion.png",
    "motionFrameCount": 24,
    "combatFrameCount": 28,
    "name": "BINARY",
    "title": "The Disruptor",
    "color": "#99b8bd",
    "description": "Black scarf. Cargo pockets. Break the pattern.",
    "move": "Null Sweep",
    "speed": 9,
    "power": 7,
    "reach": 7,
    "sheet": "/assets/characters/binary-sheet.png",
    "portrait": "/assets/characters/binary-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
  {
    "id": "aether",
    "combatSheet": "/assets/characters/aether-combat.png",
    "motionSheet": "/assets/characters/aether-motion.png",
    "motionFrameCount": 24,
    "combatFrameCount": 28,
    "name": "AETHER",
    "title": "The Sunrunner",
    "color": "#ffa355",
    "description": "Cream and orange. A bright streak across the arena.",
    "move": "Solar Cyclone",
    "speed": 9,
    "power": 7,
    "reach": 8,
    "sheet": "/assets/characters/aether-sheet.png",
    "portrait": "/assets/characters/aether-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
  {
    "id": "gaia",
    "combatSheet": "/assets/characters/gaia-combat.png",
    "motionSheet": "/assets/characters/gaia-motion.png",
    "motionFrameCount": 24,
    "combatFrameCount": 28,
    "name": "GAIA",
    "title": "The Alchemist",
    "color": "#72d6a8",
    "description": "A scientist in a lab coat with an unstable new formula.",
    "move": "Root Uprising",
    "speed": 5,
    "power": 9,
    "reach": 10,
    "sheet": "/assets/characters/gaia-sheet.png",
    "portrait": "/assets/characters/gaia-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
  {
    "id": "zenith",
    "combatSheet": "/assets/characters/zenith-combat.png",
    "motionSheet": "/assets/characters/zenith-motion.png",
    "motionFrameCount": 24,
    "combatFrameCount": 28,
    "name": "ZENITH",
    "title": "The Strategist",
    "color": "#b5a5ee",
    "description": "Braids, glasses, and a gray turtleneck. Always one step ahead.",
    "move": "Apex Pulse",
    "speed": 7,
    "power": 9,
    "reach": 6,
    "sheet": "/assets/characters/zenith-sheet.png",
    "portrait": "/assets/characters/zenith-portrait.png",
    "frameWidth": 320,
    "frameHeight": 320,
    "frameCount": 16,
    "frameDuration": 65,
    "bodyHeight": 176,
    "anchorX": 160,
    "anchorY": 296,
    "originalDuration": 160
  },
];
export default characters;
